---
- block:
  - name: install compiling tools
    apt: "pkg={{ packages }} state=latest"
    vars:
      packages:
      - git
      - libpcre3-dev
  - name: create uwsgi virtualenv
    shell: "python3 -m venv /opt/uwsgi"
    args:
      creates: "/opt/uwsgi"
  - name: install wheel
    shell: "/opt/uwsgi/bin/pip install wheel"
  # XXX: uwsgi 2.0.18 has bug, so use forking version instead.
  #      See https://github.com/unbit/uwsgi/issues/1978
  - name: install uwsgi
    shell: "/opt/uwsgi/bin/pip install git+https://github.com/onsigntv/uwsgi.git@2.0.18-forking-fix"
  - name: create uwsgi config dir
    file: "path=/opt/uwsgi/etc owner=root group=root mode=0755 state=directory"
  - name: setup uwsgi systemd service file
    copy:
      src: "uwsgi.service"
      dest: "/etc/systemd/system/uwsgi.service"
      owner: "root"
      group: "root"
      mode: "0644"
  - name: enable uwsgi service at startup
    service: "name=uwsgi.service enabled=yes"
  tags:
    - uwsgi
