---
- block:
  - name: install compiling tools
    apt: "pkg=libpcre3-dev state=latest"
  - name: create uwsgi virtualenv
    shell: "python3 -m venv /opt/uwsgi"
    args:
      creates: "/opt/uwsgi"
  - name: install wheel
    shell: "/opt/uwsgi/bin/pip install wheel"
  - name: install uwsgi
    shell: "/opt/uwsgi/bin/pip install uwsgi=={{ uwsgi_version }}"
  - name: create uwsgi config dir
    file: "path=/opt/uwsgi/etc owner=root group=root mode=0755 state=directory"
  - name: setup uwsgi systemd service file
    copy:
      src: "uwsgi.service"
      dest: "/etc/systemd/system/uwsgi.service"
      owner: "root"
      group: "root"
      mode: "0644"
  - name: enable uwsgi service at startup
    systemd:
      name: "uwsgi.service"
      enabled: yes
      daemon_reload: yes
      state: started
  tags:
    - uwsgi
